version: '3'
services:
  web:
    build: .
    ports:
      - '8080:80'
    depends_on:
      - db
    volumes:
      - ./src/:/var/html/www
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: gameworld
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - '8181:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db_data
